program Boss4D.GUI;

uses
  Vcl.Forms,

  Boss4D.GUI.Main in 'Boss4D.GUI.Main.pas' {FormMain},
  Boss4D.GUI.IDE.Presenter in 'Boss4D.GUI.IDE.Presenter.pas',
  Boss4D.GUI.IDE.Install.Presenter in 'Boss4D.GUI.IDE.Install.Presenter.pas',
  Boss4D.GUI.IDE.Timeline in 'Boss4D.GUI.IDE.Timeline.pas',
  Boss4D.GUI.IDE.Dashboard in 'Boss4D.GUI.IDE.Dashboard.pas',
  Boss4D.GUI.Logs in 'Boss4D.GUI.Logs.pas',
  Boss4D.GUI.IDE.Dashboard.Dialog in 'Boss4D.GUI.IDE.Dashboard.Dialog.pas',
  Boss4D.GUI.IDE.Timeline.Dialog in 'Boss4D.GUI.IDE.Timeline.Dialog.pas',
  Boss4D.GUI.IDE.Backend in 'Boss4D.GUI.IDE.Backend.pas',
  Boss4D.Core.Domain.Consts in '..\Core\Domain\Boss4D.Core.Domain.Consts.pas',
  Boss4D.Core.Domain.Env in '..\Core\Domain\Boss4D.Core.Domain.Env.pas',
  Boss4D.Core.Domain.SemVer in '..\Core\Domain\Boss4D.Core.Domain.SemVer.pas',
  Boss4D.Core.Domain.Dependency in '..\Core\Domain\Boss4D.Core.Domain.Dependency.pas',
  Boss4D.Core.Domain.Package in '..\Core\Domain\Boss4D.Core.Domain.Package.pas',
  Boss4D.Core.Domain.BuildMatrix in '..\Core\Domain\Boss4D.Core.Domain.BuildMatrix.pas',
  Boss4D.Core.Domain.Lock in '..\Core\Domain\Boss4D.Core.Domain.Lock.pas',
  Boss4D.Core.Domain.Sbom in '..\Core\Domain\Boss4D.Core.Domain.Sbom.pas',
  Boss4D.Core.Domain.License in '..\Core\Domain\Boss4D.Core.Domain.License.pas',
  Boss4D.Core.Domain.Progress in '..\Core\Domain\Boss4D.Core.Domain.Progress.pas',
  Boss4D.Core.Domain.IDEProfile in '..\Core\Domain\Boss4D.Core.Domain.IDEProfile.pas',
  Boss4D.Core.Ports in '..\Core\Ports\Boss4D.Core.Ports.pas',
  Boss4D.Core.Platform in '..\Core\Platform\Boss4D.Core.Platform.pas',
  Boss4D.Adapters.Platform.Windows in '..\Adapters\Platform\Windows\Boss4D.Adapters.Platform.Windows.pas',
  Boss4D.Adapters.Json in '..\Adapters\Json\Boss4D.Adapters.Json.pas',
  Boss4D.Adapters.Http in '..\Adapters\Http\Boss4D.Adapters.Http.pas',
  Boss4D.Adapters.Git in '..\Adapters\Git\Boss4D.Adapters.Git.pas',
  Boss4D.Adapters.Registry in '..\Adapters\Registry\Boss4D.Adapters.Registry.pas',
  Boss4D.Adapters.Compiler in '..\Adapters\Compiler\Boss4D.Adapters.Compiler.pas',
  Boss4D.Adapters.Logger in '..\Adapters\Logger\Boss4D.Adapters.Logger.pas',
  Boss4D.Adapters.Security.Windows in '..\Adapters\Security\Boss4D.Adapters.Security.Windows.pas',
  Boss4D.Adapters.Security.Gpg in '..\Adapters\Security\Boss4D.Adapters.Security.Gpg.pas',
  Boss4D.Core.Services.Init in '..\Core\Services\Boss4D.Core.Services.Init.pas',
  Boss4D.Core.Services.Config in '..\Core\Services\Boss4D.Core.Services.Config.pas',
  Boss4D.Core.Services.Install in '..\Core\Services\Boss4D.Core.Services.Install.pas',
  Boss4D.Core.Services.OperationGate in '..\Core\Services\Boss4D.Core.Services.OperationGate.pas',
  Boss4D.Core.Services.SelfUpdate in '..\Core\Services\Boss4D.Core.Services.SelfUpdate.pas',
  Boss4D.Core.Services.Pack in '..\Core\Services\Boss4D.Core.Services.Pack.pas',
  Boss4D.Core.Services.Resolver in '..\Core\Services\Boss4D.Core.Services.Resolver.pas',
  Boss4D.Core.Services.Conformance in '..\Core\Services\Boss4D.Core.Services.Conformance.pas',
  Boss4D.Core.Services.RegistryPortal in '..\Core\Services\Boss4D.Core.Services.RegistryPortal.pas',
  Boss4D.Core.Services.Progress in '..\Core\Services\Boss4D.Core.Services.Progress.pas',
  Boss4D.Core.Services.Transaction in '..\Core\Services\Boss4D.Core.Services.Transaction.pas',
  Boss4D.Core.Services.Dependencies in '..\Core\Services\Boss4D.Core.Services.Dependencies.pas',
  Boss4D.Core.Services.VersionHistory in '..\Core\Services\Boss4D.Core.Services.VersionHistory.pas',
  Boss4D.Core.Services.Audit in '..\Core\Services\Boss4D.Core.Services.Audit.pas',
  Boss4D.Core.Services.PackageIndex in '..\Core\Services\Boss4D.Core.Services.PackageIndex.pas',
  Boss4D.GUI.Catalog.Presenter in 'Boss4D.GUI.Catalog.Presenter.pas',
  Boss4D.GUI.Install.Presenter in 'Boss4D.GUI.Install.Presenter.pas',
  Boss4D.GUI.Install.Dialog in 'Boss4D.GUI.Install.Dialog.pas',
  Boss4D.GUI.Operation.Presenter in 'Boss4D.GUI.Operation.Presenter.pas',
  Boss4D.GUI.Process.Windows in 'Boss4D.GUI.Process.Windows.pas',
  Boss4D.GUI.Health.Presenter in 'Boss4D.GUI.Health.Presenter.pas',
  Boss4D.Core.Services.DependencySubmission in '..\Core\Services\Boss4D.Core.Services.DependencySubmission.pas',
  Boss4D.Core.Services.ArtifactCache in '..\Core\Services\Boss4D.Core.Services.ArtifactCache.pas',
  Boss4D.Core.Services.BuildMatrix in '..\Core\Services\Boss4D.Core.Services.BuildMatrix.pas',
  Boss4D.Core.Services.BuildConventions in '..\Core\Services\Boss4D.Core.Services.BuildConventions.pas',
  Boss4D.Core.Services.BuildCapabilities in '..\Core\Services\Boss4D.Core.Services.BuildCapabilities.pas',
  Boss4D.Core.Services.BuildSpec in '..\Core\Services\Boss4D.Core.Services.BuildSpec.pas',
  Boss4D.Core.Services.BuildCommand in '..\Core\Services\Boss4D.Core.Services.BuildCommand.pas',
  Boss4D.Core.Services.BuildDoctor in '..\Core\Services\Boss4D.Core.Services.BuildDoctor.pas',
  Boss4D.Core.Services.BuildPaths in '..\Core\Services\Boss4D.Core.Services.BuildPaths.pas',
  Boss4D.Core.Services.BuildExecutor in '..\Core\Services\Boss4D.Core.Services.BuildExecutor.pas',
  Boss4D.Core.Services.BuildGraph in '..\Core\Services\Boss4D.Core.Services.BuildGraph.pas',
  Boss4D.Core.Services.ComponentPlan in '..\Core\Services\Boss4D.Core.Services.ComponentPlan.pas',
  Boss4D.Core.Services.ComponentRemoval in '..\Core\Services\Boss4D.Core.Services.ComponentRemoval.pas',
  Boss4D.Core.Services.BuildState in '..\Core\Services\Boss4D.Core.Services.BuildState.pas',
  Boss4D.Core.Services.BuildScheduler in '..\Core\Services\Boss4D.Core.Services.BuildScheduler.pas',
  Boss4D.Core.Services.Cache in '..\Core\Services\Boss4D.Core.Services.Cache.pas',
  Boss4D.Core.Services.Run in '..\Core\Services\Boss4D.Core.Services.Run.pas',
  Boss4D.Core.Services.Doctor in '..\Core\Services\Boss4D.Core.Services.Doctor.pas',
  Boss4D.Core.Services.License in '..\Core\Services\Boss4D.Core.Services.License.pas',
  Boss4D.Core.Services.Tree in '..\Core\Services\Boss4D.Core.Services.Tree.pas',
  Boss4D.Core.Services.Outdated in '..\Core\Services\Boss4D.Core.Services.Outdated.pas',
  Boss4D.Core.Services.IDEIntegration in '..\Core\Services\Boss4D.Core.Services.IDEIntegration.pas',
  Boss4D.Core.Services.IDERegistration in '..\Core\Services\Boss4D.Core.Services.IDERegistration.pas',
  Boss4D.Core.Services.IDEProfiles in '..\Core\Services\Boss4D.Core.Services.IDEProfiles.pas',
  Boss4D.Core.Services.IDEProfileApplication in '..\Core\Services\Boss4D.Core.Services.IDEProfileApplication.pas',
  Boss4D.Core.Services.IDEManagementQuery in '..\Core\Services\Boss4D.Core.Services.IDEManagementQuery.pas',
  Boss4D.Core.Services.IDEOperationResult in '..\Core\Services\Boss4D.Core.Services.IDEOperationResult.pas',
  Boss4D.Core.Services.IDEProcessPolicy in '..\Core\Services\Boss4D.Core.Services.IDEProcessPolicy.pas',
  Boss4D.Core.Services.IDEOperationLock in '..\Core\Services\Boss4D.Core.Services.IDEOperationLock.pas',
  Boss4D.Core.Services.BuildInventory in '..\Core\Services\Boss4D.Core.Services.BuildInventory.pas',
  Boss4D.Core.Services.BuildCoordinator in '..\Core\Services\Boss4D.Core.Services.BuildCoordinator.pas',
  Boss4D.Core.Services.IDEDiscovery in '..\Core\Services\Boss4D.Core.Services.IDEDiscovery.pas',
  Boss4D.Core.Services.PackageInstall in '..\Core\Services\Boss4D.Core.Services.PackageInstall.pas',
  Boss4D.Core.Services.Tool in '..\Core\Services\Boss4D.Core.Services.Tool.pas',
  Boss4D.Core.Services.Workspace in '..\Core\Services\Boss4D.Core.Services.Workspace.pas',
  Boss4D.Core.Services.GetIt in '..\Core\Services\Boss4D.Core.Services.GetIt.pas',
  Boss4D.Core.Services.Scaffold in '..\Core\Services\Boss4D.Core.Services.Scaffold.pas',
  Boss4D.Core.Services.SourceNormalizer in '..\Core\Services\Boss4D.Core.Services.SourceNormalizer.pas',
  Boss4D.Core.Services.PackageManifest in '..\Core\Services\Boss4D.Core.Services.PackageManifest.pas',
  Boss4D.Core.Services.LazarusProject in '..\Core\Services\Boss4D.Core.Services.LazarusProject.pas';



begin
  ConfigureWindowsPlatform;
  Vcl.Forms.Application.Initialize;
  Vcl.Forms.Application.MainFormOnTaskBar := True;

  Vcl.Forms.Application.CreateForm(TFormMain, FormMain);
  Vcl.Forms.Application.Run;
end.
