# Metadados do Projeto
sonar.projectKey=Boss4D
sonar.projectName=Boss4D
sonar.projectVersion=1.0.0

# Caminhos de Fontes e Testes
sonar.sources=src
sonar.tests=tests

# Codificacao dos arquivos fonte
sonar.sourceEncoding=UTF-8

# Padrao de exclusao (ignorar modulos baixados e lixos)
sonar.exclusions=**/modules/**,**/bin/**,**/*.log,**/*.bat,**/__history/**,**/__recovery/**

# URL do Servidor do SonarQube (padrao local, altere se necessario)
sonar.host.url=http://localhost:9000

# Integracao de Relatorios de Testes Unitarios (DUnitX / NUnit)
sonar.delphi.nunit.reportPaths=tests
